config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  resources :questions do
  	resources :answers
  end

  resources :answers do
  	resources :reviews
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get 'sessions/destroy'

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	has_many :answers
	validates :qtext, presence: false
	validates :description, presence: true, length: {minimum: 10}
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :answer
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reviews
  has_many :answers
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:twitter]

  	def self.from_omniauth(auth)
	  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		    user.email = auth.info.email
		    user.password = Devise.friendly_token[0,20]
		    # If you are using confirmable and the provider(s) you use validate emails, 
		    # uncomment the line below to skip the confirmation emails.
		    # user.skip_confirmation!
	  	end
	end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		@question = Question.find(params[:question_id])
		if(current_user)
			@answer = @question.answers.create(answer_params.merge(user_id: current_user.id, name: current_user.name))
			@answer.name = current_user.name
			puts @answer.name
		else
			puts session[:omniauth]['uid']
			@answer = @question.answers.create(answer_params.merge(user_id: 1, name: session[:omniauth]['info']['name'] ))
			puts @answer.name
		end
		puts answer_params
		redirect_to question_path(@question)
	end

	def destroy
		@question = Question.find(params[:question_id])
		@answer = @question.answers.find(params[:id])
		@answer.destroy
		redirect_to question_path(@question)
	end

	def show
		if @answer.reviews.blank?
			@average_review = 0
		else
			@average_review = @answer.reviews.average(:rating).round(2)
		end
	end
	
	private def answer_params
		params.require(:answer).permit(:body)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
        end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def new
  		@question = Question.new()
	end

	def index
		@questions = Question.all.order("created_at DESC").paginate(page: params[:page], per_page: 7)
	end

	def show
		@question = Question.find(params[:id])
	end

	def create
		#render plain: params[:post].inspect
		if(current_user)
			@question = Question.new(question_params.merge(user_id: current_user.id, name: current_user.name))
		else
			@question = Question.new(question_params.merge(user_id: 1, name: session[:omniauth]['info']['name']))
		end
		if(@question.save)
			uri = URI('http://127.0.0.1:5000/stuff')
			response = Net::HTTP.post_form(uri, 'question' => @question.qtext, 'text' => @question.description)
			result = JSON.parse(response.body)
			result.to_s
			puts result
			if (current_user)
				@answer = @question.answers.create(body: result, user_id: 1, name: "deepqa")
			else
				@answer = @question.answers.create(body: result, user_id: 1, name: "deepqa")
			end
			redirect_to @question
		else
			render "new"
		end
	end


	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])
		if(@question.update(question_params))
			redirect_to @question
		else
			render 'edit'
		end
	end

	def destroy
		@question = Question.find(params[:id])
		@question.destroy

		redirect_to questions_path
	end


	private def question_params
		params.require(:question).permit(:qtext, :description)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_answer
	before_action :find_review, only: [:edit, :update]
	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.answer_id = @answer.id
		if current_user
			@review.user_id = current_user.id
		elsif session[:omniauth]
			@review.user_id = 1
		end
		if @review.save
			@question = @answer.question
			redirect_to question_path(@question)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		@review = Review.find(params[:id])

		if @review.update(review_params)
			@question = @answer.question
			redirect_to question_path(@question)
		else
			render 'edit'
		end
	end

	private
		def review_params
			params.require(:review).permit(:rating)
		end

		def find_answer
			@answer = Answer.find(params[:answer_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def destroy
		session[:user_id] = nil
		session[:omniauth] = nil
		redirect_to root_url, notice: "signed out successfully"

	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      auth = request.env["omniauth.auth"].except("extra")
      session[:omniauth] = auth
      user = User.from_omniauth(auth)
      session[:user_id] = user.id
      redirect_to root_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/answers/_answers.html.erb
<h3>Answers</h3>
<% current_time = DateTime.now %>
<% @question.answers.all.order("created_at DESC").each do |answer| %>
	<% question_time = answer.created_at %>
	<div class="well">
		<li><h4><%= image_tag('normal.png', width: '50', height: '50', class: 'image-circle')%> <%= answer.name%></h4>
		<h6>Answered <%= distance_of_time_in_words(current_time, question_time)  %>  ago</h6></li>
		<br/>
	 <div>Ans:
		 <% if answer.body.length > 200 %>
			 <%= truncate(answer.body, length: 200) %>
			 <%= link_to '...Read more', '', class: "read-more-#{@question.id}-#{answer.id}" %>
			 <script>
				 $('.read-more-<%= question.id %>-<%= answer.id %>').on('click', function(e) {
				 e.preventDefault()
				 $(this).parent().html('<%= escape_javascript question.answers.order("created_at").last.body %>')
				 })
			 </script>
		 <% else %>
			 <%= answer.body %>
	     <% end %>
	     <div>
	 		<h2> Average rating </h2>
	 		<% if answer.reviews.blank? %>
	 			<div class="average-review-rating" data-score=<%= 0 %>></div>
	 			<span>Based on <%= answer.reviews.count %> reviews </span>
	 		<% else %>
				<div class="average-review-rating" data-score=<%= answer.reviews.average(:rating).present? ? answer.reviews.average(:rating).round(2) : 0%>>
				</div>
	 			<span>Based on <%= answer.reviews.count %> reviews </span>
	 		<% end %>
	 	 </div>
 </div>
	<% if current_user %>
	 	<% if answer.user_id == current_user.id %>
			<%= link_to  [answer.question, answer],
					method: :delete,
					data: {confirm: 'Are you sure?'} do %><%= image_tag('bin.png', width: '40', height: '40', class: 'image-circle')%>
	  	<%end%>
		<% end %>
		<div>
			<% review = answer.reviews.find_by(user_id: current_user.id) %>
			<% if (answer.reviews.find_by(user_id: current_user.id)) %>
				<%= link_to "update Review", edit_answer_review_path(answer, review) %>
			<% else %>
				<%= link_to "Add Review", new_answer_review_path(answer) %>
			<% end %>
		</div>
	<% elsif session[:omniauth] %>
		<%= link_to "Add Review", new_answer_review_path(answer) %>
		<% if answer.name ==  session[:omniauth]['info']['name']%>
			<%= link_to  [answer.question, answer],
				method: :delete,
				data: {confirm: 'Are you sure?'} do %><%= image_tag('bin.png', width: '40', height: '40', class: 'image-circle')%><%end%>
		<% end %>
	<% end %>
		</p>
	</div>
<% end %>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/answers/_form.html.erb
<h3>Answer this question</h3>

<%= form_for([@question, @question.answers.build]) do |f| %>

	<p>
		<%= f.label :body, "Answer" %><br/>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-default', :value => 'Submit'}) %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "App" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->


    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <!--  <a class="navbar-brand" href=<%root_url%>>App</a>-->
        <% @auth = session[:omniauth] if session[:omniauth] %>

        <div class="navbar-collapse collapse navbar-responsive-collapse">

          <ul class="nav navbar-nav">
            <% if current_user or @auth%>
              <li><h1><%= link_to root_url do %><%= image_tag('home.png', width: '60', height: '60', class: 'image-circle')%><%end%> </h1></li>
            <% else %>
                <li><%= link_to "REGISTER",  new_user_registration_path  %></li>
                <li><%= link_to "LOGIN", new_user_session_path  %></li>
                <li>
</li>
            <% end %>
          </ul>

        <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li>   </li>
              <li>
                <br>
                <%= image_tag('normal.png', width: '50', height: '50', class: 'image-circle')%></li>
            <li><br><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

              </li>
            <% elsif @auth %>
              <li>
                <br>
                <%= image_tag(@auth['info']['image'], width: '50', height: '50', class: 'image-circle')%></li>
                <li><br><%= link_to "Logout", {:controller => "sessions", :action => "destroy"} %>
              </li>

            <% end  %>
          </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <% if current_user or @auth%>
                  <li><%= link_to "Ask a question", new_question_path %></li>
                  <br>
                  <li><%= image_tag("serc.jpg", width: '200', height: '200', class: 'image-circle')%></li>
              <% else %>
                  <li><%= image_tag("bg.png", width: '200', height: '200', class: 'image-circle')%></li>
              <% end %>

            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= form_for :question, url: question_path(@question), method: :patch do |f| %>

	<% if @question.errors.any? %>
		<% @question.errors.full_messages.each do |msg| %>
			<div class = "alert alert-danger"><%= msg %></div>
		<% end %>	
	<% end %>	


	<p>
		<%= f.label :qtext, 'What is your question?' %><br/>
		<%= f.text_field(:qtext, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :description, 'Detailed description' %><br/>
		<%= f.text_area(:description, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary', :value => 'Submit'}) %>
	</p>

<% end %>

app/views/questions/index.html.erb
<html>
<head>
</head>

<body>
<% @auth = session[:omniauth] if session[:omniauth] %>

<% if current_user or @auth %>
	<% current_time = DateTime.now %>
	<% @questions.each do |question| %>
		<div class="well">

			<h3><%= link_to question.description, question_path(question) %></h3>
			<% question_time = question.created_at	 %>
			<h6>Asked by <%= question.name %> <%= distance_of_time_in_words(current_time, question_time)  %>  ago</h6>
		</div>
		<% end  %>
		<%= will_paginate @questions %>
<% else %>
	<h1 style="text-align:center"> Q/A App </h1>
	<h2 style="text-align:center"> A place to share knowledge </h2>

<% end %>
</body>

app/views/questions/new.html.erb
<h1>Ask question</h1>

<%= form_for :question, url: questions_path do |f| %>

	<% if @question.errors.any? %>
		<% @question.errors.full_messages.each do |msg| %>
			<div class = "alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>



	<p>
		<%= f.label :description, 'What is your Question?' %><br/>
		<%= f.text_area(:description, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary', :value => 'Submit'}) %>
	</p>
<% end %>

app/views/questions/show.html.erb
<% @auth = session[:omniauth] if session[:omniauth] %>




<h1><%= @question.description %></h1>
<hr>
<% if current_user %>
	<% if @question.user_id == current_user.id%>
		<%= link_to "Edit", edit_question_path(@question), :class => 'btn btn-default' %>

		<%= link_to "Delete", question_path(@question),
							method: :delete,
							data: {confirm: 'Are you sure?'},

							:class => 'btn btn-danger' %>
	<% end %>
<% elsif session[:omniauth]%>
	<% if @question.name == session[:omniauth]['info']['name'] %>
		<%= link_to "Edit", edit_question_path(@question), :class => 'btn btn-default' %>

		<%= link_to "Delete", question_path(@question),
							method: :delete,
							data: {confirm: 'Are you sure?'},

							:class => 'btn btn-danger' %>
	<% end %>
<% end %>
<hr>
<%= render 'answers/answers' %>
<hr>
<%= render 'answers/form' %>
<hr>

app/views/reviews/_form.html.erb
<%= form_for([@answer, @answer.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">

		<h1>Edit Review</h1>

		<%= form_for([@answer, @review]) do |f| %>
			<div id="rating-form">
				<label>Rating</label>
			</div>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>	

	</div>

</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<h1> New Review </h1>
<%= render 'form' %>